server:
  port: 8087
spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: mongodb://root:heiya@localhost:27017
      database: PlazaLeyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
leyou:
  jwt:
    secret: Plazaleyou@Login(Auth}*^20180322)&Heiya%
    pubKeyPath: D:\\aaa\\rsa\\rsa.pub # public key direction
    priKeyPath: D:\\aaa\\rsa\\rsa.pri # private key direction
    expire: 30
    cookieName: PLY_TOKEN