server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.19.128
    username: leyou
    password: leyou
    virtual-host: /leyou
leyou:
  sms:
    accessKeyId: LTAItNxtDfk7MJMq
    accessKeySecret: aySRliswq8fe7rF9gQyy1Izz4MQ
    signName: Plaza Leyou
    verifyCodeTemplate: SMS_133976814