server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB # set file size
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 240
    height: 240
  tracker-list: #tracker direcction：vm+port（22122）
    - 192.168.19.128:22122