server:
  port: 8084
spring:
  application:
    name: goods-web
  thymeleaf:
    cache: false #only during development. For production the value is true
  rabbitmq:
    host: 192.168.19.128
    username: leyou
    password: leyou
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15