server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3307/plazaleyou?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: heiya
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    generate-ddl: true
  data:
    mongodb:
      uri: mongodb://root:heiya@localhost:27017
      database: PlazaLeyou
  rabbitmq:
    host: 192.168.19.128
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      exchange: LEYOU.SMS.EXCHANGE
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15